on load:
	set {_name} to "Greeter"
	if {npc.%{_name}%.prefix} is not set:
		set {npc.%{_name}%.prefix} to "&b[Greeter]&f:"
on chat:
	set {_name} to "Greeter"
	if message contains "hi" or "hey" or "hello" or "sup" or "heyy" or "help":
		loop entities in radius 6 around player:
			if name of citizen citizen id of loop-value is {_name}:
				wait 1 tick
				message "%{npc.%{_name}%.prefix}% Welcome to Padra!"
